[package]
name = "diversion"
version = "0.1.1"
edition = "2024"

[[bin]]
path = "./main.rs"
name = "diversion"

[dependencies]
structopt = "0.3.26"

[dependencies.nix]
version = "0.24.1"
features = ["ioctl"]

[dependencies.mlua]
version = "0.11"
features = ["lua54"]
